/** Generated by YAKINDU Statechart Tools code generator. */

import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.LinkedList;
import java.util.Queue;

public class Statechart implements IStatemachine, ITimed {
	public enum State {
		MAIN_REGION_ON,
		MAIN_REGION_OFF,
		MAIN_REGION_ONTIMER,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[1];
	
	private Queue<Runnable> inEventQueue = new LinkedList<Runnable>();
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		return isExecuting;
	}
	
	protected void setIsExecuting(boolean value) {
		this.isExecuting = value;
	}
	public Statechart() {
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		
		isExecuting = false;
	}
	
	public void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		enterSequence_main_region_default();
		isExecuting = false;
	}
	
	public void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		exitSequence_main_region();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		on = false;
		off = false;
		timerOn = false;
		timeEvents[0] = false;
	}
	
	private void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		nextEvent();
		do { 
			for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
				switch (stateVector[nextStateIndex]) {
				case MAIN_REGION_ON:
					main_region_On_react(true);
					break;
				case MAIN_REGION_OFF:
					main_region_Off_react(true);
					break;
				case MAIN_REGION_ONTIMER:
					main_region_OnTimer_react(true);
					break;
				default:
					// $NULLSTATE$
				}
			}
			
			clearInEvents();
			nextEvent();
		} while ((((on || off) || timerOn) || timeEvents[0]));
		
		isExecuting = false;
	}
	
	protected void nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return;
		}
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case MAIN_REGION_ON:
			return stateVector[0] == State.MAIN_REGION_ON;
		case MAIN_REGION_OFF:
			return stateVector[0] == State.MAIN_REGION_OFF;
		case MAIN_REGION_ONTIMER:
			return stateVector[0] == State.MAIN_REGION_ONTIMER;
		default:
			return false;
		}
	}
	
	public void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public void raiseTimeEvent(int eventID) {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timeEvents[eventID] = true;
			}
		});
		runCycle();
	}
	
	private boolean on;
	
	
	public void raiseOn() {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				on = true;
			}
		});
		runCycle();
	}
	
	private boolean off;
	
	
	public void raiseOff() {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				off = true;
			}
		});
		runCycle();
	}
	
	private boolean timerOn;
	
	
	public void raiseTimerOn() {
		inEventQueue.add(new Runnable() {
			@Override
			public void run() {
				timerOn = true;
			}
		});
		runCycle();
	}
	
	/* Entry action for state 'On'. */
	private void entryAction_main_region_On() {
		timerService.setTimer(this, 0, (60 * 1000), false);
	}
	
	/* Exit action for state 'On'. */
	private void exitAction_main_region_On() {
		timerService.unsetTimer(this, 0);
	}
	
	/* 'default' enter sequence for state On */
	private void enterSequence_main_region_On_default() {
		entryAction_main_region_On();
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_REGION_ON;
	}
	
	/* 'default' enter sequence for state Off */
	private void enterSequence_main_region_Off_default() {
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_REGION_OFF;
	}
	
	/* 'default' enter sequence for state OnTimer */
	private void enterSequence_main_region_OnTimer_default() {
		nextStateIndex = 0;
		stateVector[0] = State.MAIN_REGION_ONTIMER;
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* Default exit sequence for state On */
	private void exitSequence_main_region_On() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_main_region_On();
	}
	
	/* Default exit sequence for state Off */
	private void exitSequence_main_region_Off() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state OnTimer */
	private void exitSequence_main_region_OnTimer() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[0]) {
		case MAIN_REGION_ON:
			exitSequence_main_region_On();
			break;
		case MAIN_REGION_OFF:
			exitSequence_main_region_Off();
			break;
		case MAIN_REGION_ONTIMER:
			exitSequence_main_region_OnTimer();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_On_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean main_region_On_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (off) {
				exitSequence_main_region_On();
				enterSequence_main_region_Off_default();
				react();
			} else {
				if (timerOn) {
					exitSequence_main_region_On();
					enterSequence_main_region_OnTimer_default();
					react();
				} else {
					if (timeEvents[0]) {
						exitSequence_main_region_On();
						enterSequence_main_region_OnTimer_default();
						react();
					} else {
						did_transition = false;
					}
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_Off_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (on) {
				exitSequence_main_region_Off();
				enterSequence_main_region_On_default();
				react();
			} else {
				if (timerOn) {
					exitSequence_main_region_Off();
					enterSequence_main_region_OnTimer_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
	private boolean main_region_OnTimer_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (off) {
				exitSequence_main_region_OnTimer();
				enterSequence_main_region_Off_default();
				react();
			} else {
				if (on) {
					exitSequence_main_region_OnTimer();
					enterSequence_main_region_On_default();
					react();
				} else {
					did_transition = false;
				}
			}
		}
		if (did_transition==false) {
			did_transition = react();
		}
		return did_transition;
	}
	
}
